version: '3.8'
services:
  stats-server:
    build: stat/stat-service
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6432:5432"  # внешний доступ: 6432  внутренний 5432
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - STAT_CLIENT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6433:5432"  # внешний доступ: 6433  внутренний 5432
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345